### PR TITLE
Add request_id in UI Logs 

### PR DESCRIPTION
**Pull request by purushothaman-source**
Added requestid and using the UUID if  UI passed in logs

### CODE REVIEW

**Comment by purushothaman-source** [comment]
Pr under review

**Comment by prashanthellina** [comment]
@purushothaman-source Please post more information in PRs and Issues. There is no way for me to examine the new log format so I can ensure that it is as expected. If you don't know how to write better updates, please take a look at how @kartikdc and @shivam05011996 do it.

**Comment by purushothaman-source** [comment]
@prashanthellina   I added request_id inside info and used UUID if UI sent any otherwise generating new UUID.

I'm not able to post exact format without merging this pr ..

Screenshot from 2022-11-22 12-03-11


```js
 {"name": "/usr/local/bin/github_sync", "info": {"UUID": "a7291a49-a619-48cf-ab33-fede4109388c", "timestamp": 1668924977899, "message": "Apollo Error", "level": "exception", "url": "http://localhost/sett
ings", "host_url": "localhost", "misc": {"data": {"networkError": {"response": {}, "statusCode": 400, "result": [{"loc": ["location_id"], "msg": "value is not a valid integer", "type": "type_error.intege
r"}]}, "operation": {"variables": {}, "extensions": {}, "operationName": "GetUserLocation", "query": {"kind": "Document", "definitions": [{"kind": "OperationDefinition", "operation": "query", "name": {"k
ind": "Name", "value": "GetUserLocation"}, "variableDefinitions": [{"kind": "VariableDefinition", "variable": {"kind": "Variable", "name": {"kind": "Name", "value": "locationId"}}, "type": {"kind": "Name
dType", "name": {"kind": "Name", "value": "ID"}}, "directives": []}], "directives": [], "selectionSet": {"kind": "SelectionSet", "selections": [{"kind": "Field", "name": {"kind": "Name", "value": "locati
on"}, "arguments": [{"kind": "Argument", "name": {"kind": "Name", "value": "locationId"}, "value": {"kind": "Variable", "name": {"kind": "Name", "value": "locationId"}}}], "directives": [{"kind": "Direct
ive", "name": {"kind": "Name", "value": "rest"}, "arguments": [{"kind": "Argument", "name": {"kind": "Name", "value": "type"}, "value": {"kind": "StringValue", "value": "Location", "block": false}}, {"ki
nd": "Argument", "name": {"kind": "Name", "value": "path"}, "value": {"kind": "StringValue", "value": "get-location/{args.locationId}", "block": false}}]}], "selectionSet": {"kind": "SelectionSet", "sele
ctions": [{"kind": "Field", "name": {"kind": "Name", "value": "id"}, "arguments": [], "directives": []}, {"kind": "Field", "name": {"kind": "Name", "value": "name"}, "arguments": [], "directives": []}, {
"kind": "Field", "name": {"kind": "Name", "value": "abbrev"}, "arguments": [], "directives": []}, {"kind": "Field", "name": {"kind": "Name", "value": "timezone"}, "arguments": [], "directives": []}, {"ki
nd": "Field", "name": {"kind": "Name", "value": "start_hour"}, "arguments": [], "directives": []}, {"kind": "Field", "name": {"kind": "Name", "value": "end_hour"}, "arguments": [], "directives": []}, {"k
ind": "Field", "name": {"kind": "Name", "value": "__typename"}}]}}]}}], "loc": {"start": 0, "end": 221, "source": {"body": "query GetUserLocation($locationId: ID) {\n  location(locationId: $locationId)\n
    @rest(type: \"Location\", path: \"get-location/{args.locationId}\") {\n    id\n    name\n    abbrev\n    timezone\n    start_hour\n    end_hour\n  }\n}\n", "name": "GraphQL request", "locationOffset"
: {"line": 1, "column": 1}}}}}}}, "event": "Apollo Error"}, "is_ui_log": true, "level": "error", "event": "Apollo Error", "timestamp": "2022-11-20T06:16:22.499544Z", "id": "20221120T061622_dae438fc689a11
edab640242ac13000b", "type": "log", "host": "be291e346b2e", "exception": "NoneType: None"}
```

**Comment by purushothaman-source** [comment]
Waiting for review

**Comment by purushothaman-source** [comment]
> Waiting for review

**Comment by purushothaman-source** [comment]
> Waiting for review

**Pull request merged**
